### ISSUE TITLE
Work around for error 0x8000ffff on deploy (principally for windows 11 users)

### ISSUE THREAD

**Issue by Xarkam** [ChromaControl/ChromaControl#160]
I there, 

for installing (deploying for msixbundle) the app, open a terminal and type this command followed with the location of bundle:

` add-appxpackage -path  C:\Users\xarkam\Downloads\ChromaControl_0.1.3.0_x86_x64.msixbundle`
**Of course, adapt the path to your situation**
![image](https://user-images.githubusercontent.com/331816/147562824-fff5e2eb-7bc9-42b4-a05d-ca260c772502.png)

After, retrieve it in recent items on start menu:
![image](https://user-images.githubusercontent.com/331816/147562636-7506a9e6-bc4f-4c8e-9067-03620015ad15.png)

**Comment by lux3or** [comment]
Attempted this workaround by running PS as admin. I got the following error. 
Notes: This is a little more verbose than what it told me when I attempted to directly install from the msixbundle file after downloading, but it's the same issue. When I attempted to download/install directly from the web/ repo, it said that the ms-appinstaller protocol has been disabled. The advisory in the PS response to check the logs was a lie. There's no additional information provided by Windows to be of help, sorry Dev!

_Looking further into the ms-appinstaller protocol being disabled, turns out it was the propagation method of Emotet/ Trickbot ransomware, Nice. It was removed from service Dec 15 2021 with plans to return it "in the future" according to Microsoft devs._

**Currently using Win10 v.21H1**

```
add-appxpackage : Deployment failed with HRESULT: 0x800B0101, A required certificate is not within its validity period when verifying against the
current system clock or the timestamp in the signed file.
error 0x800B0101: Opening the package from location ChromaControl_0.1.3.0_x86_x64.msixbundle failed.
NOTE: For additional information, look for [ActivityId] 91e7db12-091e-000e-3d41-10921e09d801 in the Event Log or use the command line Get-AppPackageLog
-ActivityID 91e7db12-091e-000e-3d41-10921e09d801
At line:1 char:1
+ add-appxpackage -path C:\Users\[user]\Downloads\apps\ChromaControl\Chro ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Users\lux3\D..._x64.msixbundle:String) [Add-AppxPackage], Exception
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand
```

**Comment by AndrewBabbitt97** [comment]
Fixed with latest update,

**Comment by zepoxnyan** [comment]
Problem still persists even after latest update (version 0.1.4.)
![image](https://user-images.githubusercontent.com/15271975/181621929-818ea594-891f-4f16-9467-5708749e08f2.png)

**Comment by AndrewBabbitt97** [comment]
Was this through the msixbundle or the appinstaller file?

**Comment by Xarkam** [comment]
@zepoxnyan you can use this utility https://www.advancedinstaller.com/msix-troubleshooter.html to see exactly what is wrong.
